import { Buffer } from "node:buffer";

const TVI_BASE="https://tviplayer.iol.pt";
const TVI_LOGO=TVI_BASE+"/favicon.ico";
const CACHE_TTL_MS=15*60*1000;
const catalogCache=new Map();
const metaCache=new Map();

export const TVI_VOD_CATALOGS=Object.freeze([
  {type:"series",id:"tvi-vod-programas",name:"🇵🇹 TVI Player • Programas",url:TVI_BASE+"/programas/tvi"},
  {type:"series",id:"tvi-vod-novelas",name:"🇵🇹 TVI Player • Novelas",url:TVI_BASE+"/programas/tvi",keywords:["novela","morango","festa é festa","a fazenda","beijo do escorpiao","queridos papas","cacau"]},
  {type:"series",id:"tvi-vod-reality",name:"🇵🇹 TVI Player • Reality",url:TVI_BASE+"/programas/tvi",keywords:["big brother","casa dos segredos","secret story","dilema","reality","desafio final"]},
  {type:"series",id:"tvi-vod-informacao",name:"🇵🇹 TVI Player • Informação",url:TVI_BASE+"/programas/tvi",keywords:["jornal","noticias","notícias","informacao","informação","entrevista","cnn","exclusivo"]},
  {type:"series",id:"tvi-vod-series",name:"🇵🇹 TVI Player • Séries",url:TVI_BASE+"/programas/tvi",keywords:["serie","série","ficcao","ficção","minisserie","minissérie"]},
  {type:"series",id:"tvi-vod-entretenimento",name:"🇵🇹 TVI Player • Entretenimento",url:TVI_BASE+"/programas/tvi",keywords:["entretenimento","goucha","dois às 10","dois as 10","em familia","em família","somos portugal","a tua cara","dança","danca","talento"]},
]);

function decodeHtml(value=""){const named={amp:"&",quot:'"',apos:"'",lt:"<",gt:">",nbsp:" ",ndash:"–",mdash:"—",hellip:"…",aacute:"á",eacute:"é",iacute:"í",oacute:"ó",uacute:"ú",agrave:"à",acirc:"â",ecirc:"ê",ocirc:"ô",atilde:"ã",otilde:"õ",ccedil:"ç",Aacute:"Á",Eacute:"É",Iacute:"Í",Oacute:"Ó",Uacute:"Ú",Agrave:"À",Acirc:"Â",Ecirc:"Ê",Ocirc:"Ô",Atilde:"Ã",Otilde:"Õ",Ccedil:"Ç"};return String(value).replace(/&#x([0-9a-f]+);/gi,(_,h)=>String.fromCodePoint(parseInt(h,16))).replace(/&#([0-9]+);/g,(_,d)=>String.fromCodePoint(parseInt(d,10))).replace(/&([a-z]+);/gi,(m,k)=>named[k]??named[k.toLowerCase()]??m)}
function stripTags(value=""){return decodeHtml(String(value).replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim()}
function attrValue(attrs="",name){const safe=String(name).replace(/[.*+?^$()|[\]\\]/g,"\\$&");const m=String(attrs).match(new RegExp("(?:^|\\s)"+safe+"\\s*=\\s*([\"'])(.*?)\\1","i"));return m?decodeHtml(m[2]).trim():""}
function absoluteTviUrl(value=""){try{const u=new URL(decodeHtml(value),TVI_BASE);return u.hostname==="tviplayer.iol.pt"?u.toString():""}catch{return""}}
function absoluteHttpUrl(value=""){try{const u=new URL(decodeHtml(value),TVI_BASE);return /^https?:$/.test(u.protocol)?u.toString():""}catch{return""}}
function tviPath(value=""){try{const u=new URL(value,TVI_BASE);if(u.hostname!=="tviplayer.iol.pt")return"";const path=u.pathname.replace(/\/+/g,"/");if(!/^\/programa\/[^/]+\/[a-z0-9]+(?:\/(?:t\d+|video\/[a-z0-9]+))?\/?$/i.test(path))return"";return path.replace(/\/$/,"")+(u.search||"")}catch{return""}}
function encodeId(path){return"tvivod:"+Buffer.from(path,"utf8").toString("base64url")}
function decodeId(id=""){if(!String(id).startsWith("tvivod:"))return"";try{return tviPath(Buffer.from(String(id).slice(7),"base64url").toString("utf8"))}catch{return""}}
async function fetchHtml(target){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(target,{signal:controller.signal,redirect:"follow",headers:{Accept:"text/html,application/xhtml+xml","User-Agent":"PT-HUB/4.0 TVI-Player-Public-Catalog"}});if(!r.ok)throw new Error("TVI Player HTTP "+r.status);return await r.text()}finally{clearTimeout(timer)}}
function metaTag(html,property){const safe=String(property).replace(/[.*+?^$()|[\]\\]/g,"\\$&");for(const p of [new RegExp("<meta[^>]+(?:property|name)=[\"']"+safe+"[\"'][^>]+content=[\"']([^\"']+)[\"'][^>]*>","i"),new RegExp("<meta[^>]+content=[\"']([^\"']+)[\"'][^>]+(?:property|name)=[\"']"+safe+"[\"'][^>]*>","i")]){const m=html.match(p);if(m)return decodeHtml(m[1]).trim()}return""}
function slugTitle(path){const parts=String(path).split("/").filter(Boolean),slug=parts[1]||"TVI Player";return decodeURIComponent(slug).replace(/[-_]+/g," ").replace(/\s+/g," ").replace(/\b\p{L}/gu,c=>c.toUpperCase())}
function cleanTitle(value=""){return stripTags(value).replace(/^Aceder\s+a:\s*/i,"").replace(/^Ver\s+(?:agora|detalhes):?\s*/i,"").trim()}
function parseAnchors(html){const out=[],re=/<a\\b([^>]*?)href\\s*=\\s*([\\"\'])(.*?)\\2([^>]*)>([\\s\\S]*?)<\\/a>/gi;let m;while((m=re.exec(html)))out.push({attrs:(m[1]||"")+" "+(m[4]||""),href:absoluteTviUrl(m[3]),body:m[5]||"",start:m.index,end:re.lastIndex});return out}
function unescapeAssetUrl(value=""){return decodeHtml(String(value)).replace(/\\u0026/gi,"&").replace(/\\\//g,"/").replace(/&amp;/gi,"&")}
function firstSrcsetUrl(value=""){return String(value).split(",").map(x=>x.trim().split(/\s+/)[0]).find(Boolean)||""}
function markupImage(body=""){for(const tag of String(body).matchAll(/<(?:img|source)\b([^>]*)>/gi)){const attrs=tag[1]||"",srcset=attrValue(attrs,"srcset")||attrValue(attrs,"data-srcset"),style=attrValue(attrs,"style"),styleUrl=style.match(/url\((['"]?)(.*?)\1\)/i)?.[2]||"",raw=attrValue(attrs,"src")||attrValue(attrs,"data-src")||attrValue(attrs,"data-original")||attrValue(attrs,"data-lazy-src")||attrValue(attrs,"data-image")||attrValue(attrs,"data-background-image")||firstSrcsetUrl(srcset)||styleUrl,url=absoluteHttpUrl(unescapeAssetUrl(raw));if(url&&!/\/favicon\.ico(?:$|[?#])/i.test(url))return url}return""}
function imageFromSerializedObject(chunk=""){for(const re of [/(?:poster|imageUrl|image|thumbnail|thumb|cover|background)(?:Url)?["']?\s*[:=]\s*["']([^"']+)["']/ig,/(https?:\\?\/\\?\/[^"'<>\s]+\.(?:jpe?g|png|webp|avif)(?:\?[^"'<>\s]*)?)/ig]){let m;while((m=re.exec(chunk))){const url=absoluteHttpUrl(unescapeAssetUrl(m[1]||m[0]));if(url&&!/\/favicon\.ico(?:$|[?#])/i.test(url))return url}}return""}
function enclosingObject(text,index){for(let start=index;start>=0&&index-start<12000;start--){if(text[start]!=="{")continue;let depth=0,inString=false,quote="",escape=false;for(let i=start;i<text.length&&i-start<24000;i++){const ch=text[i];if(inString){if(escape){escape=false;continue}if(ch==="\\"){escape=true;continue}if(ch===quote){inString=false;quote=""}continue}if(ch==='"'||ch==="'"){inString=true;quote=ch;continue}if(ch==="{")depth++;else if(ch==="}"){depth--;if(depth===0){if(i>=index)return text.slice(start,i+1);break}}}}return""}
function exactSerializedProgramImage(html,root){const text=String(html);for(const needle of [root,root.replace(/\//g,"\\/")]){let at=text.indexOf(needle);while(at>=0){const object=enclosingObject(text,at);if(object&&object.includes(needle)){const image=imageFromSerializedObject(object);if(image)return image}at=text.indexOf(needle,at+needle.length)}}return""}
function enclosingCardImage(html,a){const text=String(html);for(const tag of ["article","li"]){const open=text.lastIndexOf("<"+tag,a.start);if(open<0||a.start-open>8000)continue;const close=text.indexOf("</"+tag+">",a.end);if(close<0||close-a.end>8000)continue;const nested=text.lastIndexOf("<"+tag,a.start-1);if(nested>open)continue;const block=text.slice(open,close+tag.length+3);const image=markupImage(block);if(image)return image}return""}
function anchorImage(a){return markupImage(a.body)}
function anchorTitle(a,fallback=""){const m=a.body.match(/<img\b([^>]*)>/i),img=m?.[1]||"";return cleanTitle(attrValue(a.attrs,"title")||attrValue(a.attrs,"aria-label")||attrValue(img,"alt")||stripTags(a.body))||fallback}
function programRootPath(path){return String(path).match(/^(\/programa\/[^/]+\/[a-z0-9]+)/i)?.[1]||""}
function normalized(v=""){return String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function parseCatalog(html,catalog){const metas=[],seen=new Set();for(const a of parseAnchors(html)){const path=tviPath(a.href),root=programRootPath(path);if(!root||/\/video\//i.test(path)||seen.has(root))continue;const title=anchorTitle(a,slugTitle(root));if(!title||title.length>220)continue;if(Array.isArray(catalog?.keywords)&&catalog.keywords.length&&!catalog.keywords.some(k=>normalized(title).includes(normalized(k))))continue;const poster=anchorImage(a)||enclosingCardImage(html,a)||exactSerializedProgramImage(html,root);seen.add(root);metas.push({id:encodeId(root),type:"series",name:title,...(poster?{poster,background:poster}:{poster:TVI_LOGO}),description:catalog?.name||"TVI Player",website:TVI_BASE+root});if(metas.length>=140)break}return metas}
function parseVideos(html,rootPath){const videos=[],seen=new Set();for(const a of parseAnchors(html)){const path=tviPath(a.href);if(!path||!path.startsWith(rootPath+"/video/")||seen.has(path))continue;const title=anchorTitle(a,"Episódio "+(videos.length+1)),poster=anchorImage(a);seen.add(path);videos.push({id:encodeId(path),title,season:1,episode:videos.length+1,...(poster?{thumbnail:poster}:{})});if(videos.length>=400)break}const escaped=rootPath.replace(/[.*+?^$()|[\]\\]/g,"\\$&"),embedded=new RegExp(escaped+"\\/video\\/[a-z0-9]+","gi");for(const m of String(html).matchAll(embedded)){const path=m[0].replace(/\\\//g,"/");if(seen.has(path))continue;seen.add(path);videos.push({id:encodeId(path),title:"Episódio "+(videos.length+1),season:1,episode:videos.length+1});if(videos.length>=400)break}return videos}

export async function getTviVodCatalog(type,id,search=""){if(type!=="series")return{metas:[]};const catalog=TVI_VOD_CATALOGS.find(x=>x.type===type&&x.id===id);if(!catalog)return{metas:[]};const cached=catalogCache.get(id);let metas;if(cached&&Date.now()-cached.at<CACHE_TTL_MS)metas=cached.metas;else{metas=parseCatalog(await fetchHtml(catalog.url),catalog);catalogCache.set(id,{at:Date.now(),metas})}const needle=normalized(stripTags(search));if(needle)metas=metas.filter(x=>normalized(x.name).includes(needle));return{metas:metas.slice(0,140)}}
export async function getTviVodMeta(type,id){if(type!=="series")return null;const path=decodeId(id),root=programRootPath(path);if(!root)return null;const rootId=encodeId(root),cached=metaCache.get(rootId);if(cached&&Date.now()-cached.at<CACHE_TTL_MS)return cached.meta;const website=TVI_BASE+root,html=await fetchHtml(website),title=cleanTitle(metaTag(html,"og:title"))||slugTitle(root),description=cleanTitle(metaTag(html,"og:description")||metaTag(html,"description"))||"Conteúdo TVI Player",poster=absoluteHttpUrl(metaTag(html,"og:image")),videos=parseVideos(html,root),meta={id:rootId,type:"series",name:title,description,website,videos,...(poster?{poster,background:poster}:{poster:TVI_LOGO})};metaCache.set(rootId,{at:Date.now(),meta});return meta}

function extractJsonData(html=""){const text=String(html),assign=text.search(/jsonData\s*=\s*\{/i);if(assign<0)return null;const start=text.indexOf("{",assign);if(start<0)return null;let depth=0,inString=false,quote="",escape=false;for(let i=start;i<text.length;i++){const ch=text[i];if(inString){if(escape){escape=false;continue}if(ch==="\\"){escape=true;continue}if(ch===quote){inString=false;quote=""}continue}if(ch==='"'||ch==="'"){inString=true;quote=ch;continue}if(ch==="{")depth++;else if(ch==="}"){depth--;if(depth===0){try{return JSON.parse(text.slice(start,i+1))}catch{return null}}}}return null}
function withQuery(url,key,value){const u=new URL(url);u.searchParams.set(key,value);return u.toString()}
async function resolveTviAuthorizedHls(html){const data=extractJsonData(html);if(!data?.id||!data?.videoUrl)return"";const raw=absoluteHttpUrl(data.videoUrl);if(!raw||!/\.m3u8(?:$|[?#])/i.test(raw))return"";const liveType=String(data.liveType||"").toUpperCase(),videoType=String(data.videoType||"").toUpperCase(),kind=liveType==="DIRETO"&&videoType==="LIVE"?"live":"vod";const rights=await fetch("https://services.iol.pt/direitos/rights/"+kind+"?id="+encodeURIComponent(data.id),{headers:{Referer:TVI_BASE+"/",Accept:"application/json","User-Agent":"Mozilla/5.0"}});if(!rights.ok&&rights.status!==403)return"";const body=await rights.json().catch(()=>null);if(!body||body.detail!=="ok")return"";const matrix=await fetch("https://services.iol.pt/matrix?userId=",{headers:{Referer:TVI_BASE+"/",Accept:"text/plain,*/*","User-Agent":"Mozilla/5.0"}});if(!matrix.ok)return"";const token=(await matrix.text()).trim();return token?withQuery(raw,"wmsAuthSign",token):""}

export async function getTviVodStreams(type,id){if(type!=="series")return[];const path=decodeId(id);if(!path)return[];return[{name:"PT•HUB • TVI Player",title:"Abrir no TVI Player",externalUrl:TVI_BASE+path}]}
